/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.groupproject.ewallet.ui;

import com.groupproject.ewallet.CommonUtils;
import com.groupproject.ewallet.Database;
import com.groupproject.ewallet.EWalletService;
import com.groupproject.ewallet.IEWalletService;
import com.groupproject.ewallet.Transaction;
import com.groupproject.ewallet.User;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Doodle
 */
public class EWalletUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EWalletUI.class.getName());

    private static CardLayout cardLayout;
    IEWalletService walletService;
    
    // locally stores users just so we don't do db queries everytime
    List<User> users;
    User loggedInUser;
    List<Transaction> transactions;


    /**
     * Creates new form EWalletUI
     */
    public EWalletUI() {
        initComponents();
        cardLayout = (CardLayout) cardPanel.getLayout();
        
        Database db = new Database();
        walletService = new EWalletService(db);
        loadUsers();
        transactionTableClickListener();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        cardPanel = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        regiterButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        registerUsernameLabel = new javax.swing.JLabel();
        registerFullNameField = new javax.swing.JTextField();
        registerUsernameLabel1 = new javax.swing.JLabel();
        registerUsernameLabel2 = new javax.swing.JLabel();
        registerUsernameLabel3 = new javax.swing.JLabel();
        registerEmailField = new javax.swing.JTextField();
        registerPasswordField = new javax.swing.JTextField();
        registerConfirmPasswordField = new javax.swing.JTextField();
        registerSubmit = new javax.swing.JButton();
        registerLoginLink = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JPanel();
        welcomeMessageLabel = new javax.swing.JLabel();
        profileImageLabel = new javax.swing.JLabel();
        avalableBalanceLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        actualBalanceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accountNameLabel = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        recentTransactionsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionsTable = new javax.swing.JTable();
        loginPanel = new javax.swing.JPanel();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JTextField();
        loginUsernameField = new javax.swing.JTextField();
        loginForgotPasswordLink = new javax.swing.JButton();
        registerNewAccountPrompt = new javax.swing.JLabel();
        loginSubmitButton = new javax.swing.JButton();
        loginRegisterLink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        transactPanel = new javax.swing.JPanel();
        sendMoneyLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sendMoneyButton = new javax.swing.JButton();
        transactAmountField = new javax.swing.JTextField();
        receiverComboBox = new javax.swing.JComboBox<>();
        depositPanel = new javax.swing.JPanel();
        depositAmountButton = new javax.swing.JButton();
        welcomeLabel2 = new javax.swing.JLabel();
        depositAmountField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        withdrawPanel = new javax.swing.JPanel();
        regiterButton3 = new javax.swing.JButton();
        welcomeLabel3 = new javax.swing.JLabel();
        withdrawAmountField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        resetPasswordPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        resetEmailLabel = new javax.swing.JLabel();
        resetEmailField = new javax.swing.JTextField();
        resetPasswordLabel = new javax.swing.JLabel();
        resetConfirmPasswordLabel = new javax.swing.JLabel();
        resetPasswordField = new javax.swing.JTextField();
        resetConfirmPasswordField = new javax.swing.JTextField();
        resetPasswordButton = new javax.swing.JButton();
        dashboardMenu = new javax.swing.JMenuBar();
        walletMenu = new javax.swing.JMenu();
        checkBalance = new javax.swing.JMenuItem();
        accountStatementMenu = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        editAccountMenu = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        transactMenu = new javax.swing.JMenu();
        sendMoneyMenu = new javax.swing.JMenuItem();
        depositMenu = new javax.swing.JMenuItem();
        withdrawMenu = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardPanel.setLayout(new java.awt.CardLayout());

        startPanel.setBackground(new java.awt.Color(204, 255, 255));
        startPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        regiterButton.setBackground(new java.awt.Color(153, 255, 153));
        regiterButton.setText("Register");
        regiterButton.addActionListener(this::regiterButtonActionPerformed);

        loginButton.setBackground(new java.awt.Color(153, 255, 153));
        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        welcomeLabel.setText("Hello, Welcome to EWallet...");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(welcomeLabel))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(regiterButton)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regiterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        cardPanel.add(startPanel, "LANDING_VIEW");

        registerPanel.setBackground(new java.awt.Color(204, 255, 255));
        registerPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        jLabel2.setText("Register a new E-Waller Account");

        registerUsernameLabel.setText("Full name");

        registerFullNameField.addActionListener(this::registerFullNameFieldActionPerformed);

        registerUsernameLabel1.setText("Email");

        registerUsernameLabel2.setText("Password");

        registerUsernameLabel3.setText("Confirm password");

        registerEmailField.addActionListener(this::registerEmailFieldActionPerformed);

        registerPasswordField.addActionListener(this::registerPasswordFieldActionPerformed);

        registerConfirmPasswordField.addActionListener(this::registerConfirmPasswordFieldActionPerformed);

        registerSubmit.setBackground(new java.awt.Color(153, 255, 153));
        registerSubmit.setText("Register");
        registerSubmit.addActionListener(this::registerSubmitActionPerformed);

        registerLoginLink.setBackground(new java.awt.Color(153, 255, 153));
        registerLoginLink.setText("Login");
        registerLoginLink.addActionListener(this::registerLoginLinkActionPerformed);

        jLabel3.setText("Already have an account? Click below to login");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerUsernameLabel3)
                            .addComponent(registerUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerUsernameLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerUsernameLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(registerSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(registerLoginLink)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsernameLabel1)
                    .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsernameLabel2)
                    .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsernameLabel3)
                    .addComponent(registerConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerLoginLink)
                .addGap(49, 49, 49))
        );

        cardPanel.add(registerPanel, "REGISTER_VIEW");

        dashboardPanel.setBackground(new java.awt.Color(204, 255, 255));
        dashboardPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        welcomeMessageLabel.setText("Welcome, Username");

        profileImageLabel.setBackground(new java.awt.Color(255, 102, 102));
        profileImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/groupproject/ewallet/ui/profile.png"))); // NOI18N
        profileImageLabel.setText("Profile");

        avalableBalanceLabel.setText(" ");

        jLabel7.setText("Available Balance");

        jLabel8.setText("Actual Balance");

        actualBalanceLabel.setText(" ");

        jLabel5.setText("Acount Name");

        jLabel9.setText("Acount No.");

        accountNameLabel.setText(" ");

        accountNumberLabel.setText(" ");

        recentTransactionsLabel.setText("Recent Transactions...");

        transactionsTable.setBackground(new java.awt.Color(204, 255, 255));
        transactionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DATE", "TYPE", "AMOUNT", "FEE", "FROM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionsTable);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(profileImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addComponent(accountNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(accountNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(avalableBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(actualBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recentTransactionsLabel)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(welcomeMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(accountNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(accountNumberLabel))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(avalableBalanceLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(actualBalanceLabel))))
                    .addComponent(profileImageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recentTransactionsLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardPanel.add(dashboardPanel, "DASHBOARD_VIEW");

        loginPanel.setBackground(new java.awt.Color(204, 255, 255));

        loginUsernameLabel.setText("Email");

        loginPasswordLabel.setText("Password");

        loginPasswordField.setText(" ");

        loginUsernameField.setText(" ");

        loginForgotPasswordLink.setBackground(new java.awt.Color(153, 255, 153));
        loginForgotPasswordLink.setText("Forgot Password");
        loginForgotPasswordLink.addActionListener(this::loginForgotPasswordLinkActionPerformed);

        registerNewAccountPrompt.setText("OR Register a New Account/Reset Password");

        loginSubmitButton.setBackground(new java.awt.Color(153, 255, 153));
        loginSubmitButton.setText("Login");
        loginSubmitButton.addActionListener(this::loginSubmitButtonActionPerformed);

        loginRegisterLink.setBackground(new java.awt.Color(153, 255, 153));
        loginRegisterLink.setText("Register");
        loginRegisterLink.addActionListener(this::loginRegisterLinkActionPerformed);

        jLabel1.setText("Login With Your Credentials");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginPasswordLabel)
                            .addComponent(loginUsernameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginUsernameField)
                            .addComponent(loginPasswordField)
                            .addComponent(loginSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginForgotPasswordLink)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginRegisterLink, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(registerNewAccountPrompt))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsernameLabel)
                    .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPasswordLabel)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(registerNewAccountPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginForgotPasswordLink)
                    .addComponent(loginRegisterLink))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        cardPanel.add(loginPanel, "LOGIN_VIEW");

        transactPanel.setBackground(new java.awt.Color(204, 255, 255));
        transactPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        sendMoneyLabel.setText("Send Money");

        jLabel4.setText("Amount");

        jLabel6.setText("Receiver Account");

        sendMoneyButton.setBackground(new java.awt.Color(153, 255, 153));
        sendMoneyButton.setText("Send");
        sendMoneyButton.addActionListener(this::sendMoneyButtonActionPerformed);

        transactAmountField.addActionListener(this::transactAmountFieldActionPerformed);

        receiverComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout transactPanelLayout = new javax.swing.GroupLayout(transactPanel);
        transactPanel.setLayout(transactPanelLayout);
        transactPanelLayout.setHorizontalGroup(
            transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactPanelLayout.createSequentialGroup()
                        .addGroup(transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transactAmountField)
                            .addGroup(transactPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(sendMoneyButton))
                            .addComponent(receiverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sendMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        transactPanelLayout.setVerticalGroup(
            transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(sendMoneyLabel)
                .addGap(18, 18, 18)
                .addGroup(transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(transactAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(receiverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendMoneyButton)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        cardPanel.add(transactPanel, "TRANSACT");

        depositPanel.setBackground(new java.awt.Color(204, 255, 255));
        depositPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        depositAmountButton.setBackground(new java.awt.Color(153, 255, 153));
        depositAmountButton.setText("Deposit");
        depositAmountButton.addActionListener(this::depositAmountButtonActionPerformed);

        welcomeLabel2.setText("Deposit Amount ");

        jLabel10.setText("Amount");

        javax.swing.GroupLayout depositPanelLayout = new javax.swing.GroupLayout(depositPanel);
        depositPanel.setLayout(depositPanelLayout);
        depositPanelLayout.setHorizontalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(depositPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(welcomeLabel2)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        depositPanelLayout.setVerticalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(welcomeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(depositAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(depositAmountButton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        cardPanel.add(depositPanel, "DEPOSIT");

        withdrawPanel.setBackground(new java.awt.Color(204, 255, 255));

        regiterButton3.setBackground(new java.awt.Color(153, 255, 153));
        regiterButton3.setText("Withdraw");
        regiterButton3.addActionListener(this::regiterButton3ActionPerformed);

        welcomeLabel3.setText("Withdraw Amount");

        jLabel11.setText("Amount");

        javax.swing.GroupLayout withdrawPanelLayout = new javax.swing.GroupLayout(withdrawPanel);
        withdrawPanel.setLayout(withdrawPanelLayout);
        withdrawPanelLayout.setHorizontalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(regiterButton3))
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(welcomeLabel3)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        withdrawPanelLayout.setVerticalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(welcomeLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(regiterButton3)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        cardPanel.add(withdrawPanel, "WITHDRAW");

        resetPasswordPanel.setBackground(new java.awt.Color(204, 255, 255));
        resetPasswordPanel.setPreferredSize(new java.awt.Dimension(450, 370));

        jLabel12.setText("Reset Your Password...");

        resetEmailLabel.setText("Account Email");

        resetEmailField.addActionListener(this::resetEmailFieldActionPerformed);

        resetPasswordLabel.setText("New Password");

        resetConfirmPasswordLabel.setText("Confirm password");

        resetPasswordField.addActionListener(this::resetPasswordFieldActionPerformed);

        resetConfirmPasswordField.addActionListener(this::resetConfirmPasswordFieldActionPerformed);

        resetPasswordButton.setBackground(new java.awt.Color(153, 255, 153));
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(this::resetPasswordButtonActionPerformed);

        javax.swing.GroupLayout resetPasswordPanelLayout = new javax.swing.GroupLayout(resetPasswordPanel);
        resetPasswordPanel.setLayout(resetPasswordPanelLayout);
        resetPasswordPanelLayout.setHorizontalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetConfirmPasswordLabel)
                            .addComponent(resetEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetPasswordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(resetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        resetPasswordPanelLayout.setVerticalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetEmailLabel))
                .addGap(18, 18, 18)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPasswordLabel)
                    .addComponent(resetPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetConfirmPasswordLabel)
                    .addComponent(resetConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resetPasswordButton)
                .addGap(89, 89, 89))
        );

        cardPanel.add(resetPasswordPanel, "RESET_PASS_VIEW");

        dashboardMenu.setBackground(new java.awt.Color(204, 255, 255));

        walletMenu.setText("Wallet");

        checkBalance.setText("Check Balance");
        checkBalance.addActionListener(this::checkBalanceActionPerformed);
        walletMenu.add(checkBalance);

        accountStatementMenu.setText("Account Statement");
        accountStatementMenu.addActionListener(this::accountStatementMenuActionPerformed);
        walletMenu.add(accountStatementMenu);

        dashboardMenu.add(walletMenu);

        accountMenu.setText("Account");

        editAccountMenu.setText("Edit");
        editAccountMenu.addActionListener(this::editAccountMenuActionPerformed);
        accountMenu.add(editAccountMenu);

        jMenuItem8.setText("Logout");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        accountMenu.add(jMenuItem8);

        dashboardMenu.add(accountMenu);

        transactMenu.setText("Transact");

        sendMoneyMenu.setText("Send Money");
        sendMoneyMenu.addActionListener(this::sendMoneyMenuActionPerformed);
        transactMenu.add(sendMoneyMenu);

        depositMenu.setText("Deposit");
        depositMenu.addActionListener(this::depositMenuActionPerformed);
        transactMenu.add(depositMenu);

        withdrawMenu.setText("Withdraw");
        withdrawMenu.addActionListener(this::withdrawMenuActionPerformed);
        transactMenu.add(withdrawMenu);

        dashboardMenu.add(transactMenu);

        setJMenuBar(dashboardMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginForgotPasswordLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginForgotPasswordLinkActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "RESET_PASS_VIEW");
    }//GEN-LAST:event_loginForgotPasswordLinkActionPerformed

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed

        // TODO add your handling code here:
        String email = loginUsernameField.getText().trim();
        String password = loginPasswordField.getText().trim();
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate email format
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        User auth = walletService.loginUser(email, password);
        if(auth != null){
            loggedInUser = auth;
            redirectToDashboard(auth); // Successful login
        } else {
            JOptionPane.showMessageDialog(this, "Invalid email or password", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(loggedInUser.getEmail());
    }//GEN-LAST:event_loginSubmitButtonActionPerformed

    private void loginRegisterLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRegisterLinkActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "REGISTER_VIEW");
    }//GEN-LAST:event_loginRegisterLinkActionPerformed

    private void registerFullNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerFullNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerFullNameFieldActionPerformed

    private void registerEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmailFieldActionPerformed

    private void registerPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPasswordFieldActionPerformed

    private void registerConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerConfirmPasswordFieldActionPerformed

    private void registerLoginLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLoginLinkActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "LOGIN_VIEW");
    }//GEN-LAST:event_registerLoginLinkActionPerformed

    private void accountStatementMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountStatementMenuActionPerformed
        cardLayout.show(cardPanel, "DASHBOARD_VIEW");       
    }//GEN-LAST:event_accountStatementMenuActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        cardLayout.show(cardPanel, "LOGIN_VIEW");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void regiterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiterButtonActionPerformed
        cardLayout.show(cardPanel, "REGISTER_VIEW");
    }//GEN-LAST:event_regiterButtonActionPerformed

    private void registerSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerSubmitActionPerformed
        // TODO add your handling code here:
        String fullName = registerFullNameField.getText().trim();
        String password = registerPasswordField.getText().trim();
        String confirmPassword = registerConfirmPasswordField.getText().trim();
        String email = registerEmailField.getText().trim();

        // Validate 
        if (fullName.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate email format
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate password match
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Password length --> 4 for simplicity and testing
        if (password.length() < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters long!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = walletService.registerUser(fullName, email, password);
        if (success) {
            JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            cardLayout.show(cardPanel, "LOGIN_VIEW");
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed. Email may already exist.", "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_registerSubmitActionPerformed

    private void depositAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositAmountButtonActionPerformed
        // TODO add your handling code here:
        String depositAmountText = depositAmountField.getText().trim();
        
        if (loggedInUser == null){
            login();
            return;
        }

        if (depositAmountText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amount;
        try {
            amount = Double.parseDouble(depositAmountText);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid amount format!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Amount must be greater than or = to !" + CommonUtils.MINIMUM_DEPOSIT_AMOUNT, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm deposit of Ksh. " + amount + "?",
            "Confirm Deposit",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = walletService.depositFunds(loggedInUser.getUserId(), amount);
            if (success) {
                JOptionPane.showMessageDialog(this, "Deposit successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loggedInUser.setBalance(loggedInUser.getBalance() + amount);
                redirectToDashboard(loggedInUser);
            } else {
                JOptionPane.showMessageDialog(this, "Deposit failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_depositAmountButtonActionPerformed

    private void regiterButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiterButton3ActionPerformed
        // TODO add your handling code here:
        
        if(loggedInUser == null){
            login();
            return;
        }
        
        String withdrawAmountText = withdrawAmountField.getText().trim();
        
        if (withdrawAmountText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double amount;
        try {
            amount = Double.parseDouble(withdrawAmountText);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid amount", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (amount <= 0 || amount < CommonUtils.MINIMUM_WITHDRAW_AMOUNT) {
            JOptionPane.showMessageDialog(this, "Amount must be greater than or = " + CommonUtils.MINIMUM_WITHDRAW_AMOUNT, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double fee = CommonUtils.calculateTransactionFee(amount);
        double total = amount + fee;

        if (loggedInUser.getBalance() < total) {
            JOptionPane.showMessageDialog(this, "Insufficient balance!", "Transaction Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Confirm withdrawal of Ksh. " + amount + "?" + "\nWithdraw Fee Ksh. " + fee,
            "Confirm Withdrawal",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = walletService.withdrawFunds(loggedInUser.getUserId(), amount);

            if (success) {
                JOptionPane.showMessageDialog(this, "Withdrawal successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loggedInUser.setBalance(loggedInUser.getBalance() - total);
                redirectToDashboard(loggedInUser);
            } else {
                JOptionPane.showMessageDialog(this, "Withdrawal failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_regiterButton3ActionPerformed

    private void sendMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMoneyButtonActionPerformed
        String receiverAccount = (String) receiverComboBox.getSelectedItem();
        if (loggedInUser == null){
            login();
            return;
        }
        User receiver = getLocalUser(receiverAccount);
        
        String amount = transactAmountField.getText();
        if (amount.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an amount!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println(loggedInUser == null);
        
        // convert amount to doble
        double transactAmountValue = 0.0;
        try {
            transactAmountValue = Double.parseDouble(amount);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid amount!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (transactAmountValue < CommonUtils.MINIMUM_SEND_AMOUNT) {
            JOptionPane.showMessageDialog(this, "Amount must be greater than or = to Ksh." + CommonUtils.MINIMUM_SEND_AMOUNT, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double fee = CommonUtils.calculateTransactionFee(transactAmountValue);
        double plusfee = transactAmountValue + fee;
        
        if (loggedInUser.getBalance() < plusfee) {
            JOptionPane.showMessageDialog(this, "Insufficient balance!\nAvailable Amount is Ksh. " + loggedInUser.getBalance(), "Transaction Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Send Ksh. " + amount + " to " + receiver.getName() + "?\n Transfer fee Ksh." + fee,
            "Confirm Transaction",
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = walletService.transferFunds(loggedInUser.getId(), receiver.getId(), transactAmountValue);

            if (success) {
                JOptionPane.showMessageDialog(this, "Transaction successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loggedInUser.setBalance(loggedInUser.getBalance() - plusfee);
                redirectToDashboard(loggedInUser);
            } else {
                JOptionPane.showMessageDialog(this, "Transaction failed!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Transaction cancelled!", "Success", JOptionPane.INFORMATION_MESSAGE);
            return;
        }   
    }//GEN-LAST:event_sendMoneyButtonActionPerformed

    private void transactAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactAmountFieldActionPerformed

    private void sendMoneyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMoneyMenuActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "TRANSACT");
    }//GEN-LAST:event_sendMoneyMenuActionPerformed

    private void depositMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMenuActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "DEPOSIT");
    }//GEN-LAST:event_depositMenuActionPerformed

    private void withdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawMenuActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "WITHDRAW");
    }//GEN-LAST:event_withdrawMenuActionPerformed

    private void editAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountMenuActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "EDIT_ACCOUNT");
    }//GEN-LAST:event_editAccountMenuActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "LANDING_VIEW");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void checkBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cardPanel, "DASHBOARD_VIEW");
    }//GEN-LAST:event_checkBalanceActionPerformed

    private void resetEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetEmailFieldActionPerformed

    private void resetPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetPasswordFieldActionPerformed

    private void resetConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetConfirmPasswordFieldActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        // TODO add your handling code here:
        String email = resetEmailField.getText().trim();
        String newPassword = resetPasswordField.getText().trim();
        String confirmPassword = resetConfirmPasswordField.getText().trim();

        if (email.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid email!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (newPassword.length() < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = walletService.resetPassword(email, newPassword);

        if (success) {
            JOptionPane.showMessageDialog(this, "Password reset successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            cardLayout.show(cardPanel, "LOGIN_VIEW");
        } else {
            JOptionPane.showMessageDialog(this, "Password reset failed. Invalid details", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EWalletUI().setVisible(true));
    }
    
    // helper methods
    private void redirectToDashboard(User user) {
        // Update user info
        welcomeMessageLabel.setText("Welcome, " + user.getName());
        accountNameLabel.setText(user.getName());
        accountNumberLabel.setText(user.getId());
        actualBalanceLabel.setText("Ksh. " + user.getBalance());
        avalableBalanceLabel.setText("Ksh. " + user.getBalance());

        transactions = walletService.getTransactionsForUser(user.getId());

        if (transactions != null && !transactions.isEmpty()) {
            recentTransactionsLabel.setVisible(false);

            DefaultTableModel model = (DefaultTableModel) transactionsTable.getModel();
            model.setRowCount(0); // Clear existing rows

            // Show only 5 most recent
            int limit = Math.min(transactions.size(), 5);
            for (int i = 0; i < limit; i++) {
                Transaction t = transactions.get(i);
                model.addRow(new Object[]{
                    t.getTransactionId(),
                    t.getDate(),
                    t.getType(),
                    "Ksh. " + t.getAmount(),
                    "Ksh. " + t.getFee(),
                    t.getSenderId()
                });
            }
        } else {
            transactionsTable.setVisible(false);
            recentTransactionsLabel.setText("You don't have any recent transactions...");
        }

        cardLayout.show(cardPanel, "DASHBOARD_VIEW");
    }
    
    private void loadUsers() {
        receiverComboBox.removeAllItems();
        users = walletService.getAllUsers();

        for (User u : users) {
            receiverComboBox.addItem(u.getName() + "-" + u.getUserId());
        }
    }
    
    private User getLocalUser(String selected){
        loadUsers();
        String name = selected.split("\\s*-\\s*")[0];

        for (User u : users) {
            if (name.equalsIgnoreCase(u.getName())) {
                return u;
            }
        }
        return null;
    }
    
    private void login(){
        cardLayout.show(cardPanel, "LOGIN_VIEW");
    }
    
    private void transactionTableClickListener() {
        transactionsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 1) {
                    int recordRow = transactionsTable.getSelectedRow();
                    if (recordRow != -1) {
                        displayTransactionDetails(recordRow);
                    }
                }
            }
        });
    }
    
    private void displayTransactionDetails(int recordRow){
        Transaction tx = transactions.get(recordRow);
        JOptionPane.showMessageDialog(this,
            "Type: " + tx.getType() +
            "\nAmount: Ksh. " + tx.getAmount() +
            "\nFee: Ksh. " + tx.getFee() +
            "\nSender: " + tx.getSenderId() +
            "\nReceiver: " + tx.getReceiverId(),
            "Transaction Details",
            JOptionPane.INFORMATION_MESSAGE
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMenu;
    private javax.swing.JLabel accountNameLabel;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JMenuItem accountStatementMenu;
    private javax.swing.JLabel actualBalanceLabel;
    private javax.swing.JLabel avalableBalanceLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JMenuItem checkBalance;
    private javax.swing.JMenuBar dashboardMenu;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton depositAmountButton;
    private javax.swing.JTextField depositAmountField;
    private javax.swing.JMenuItem depositMenu;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JMenuItem editAccountMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginForgotPasswordLink;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField loginPasswordField;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JButton loginRegisterLink;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JLabel profileImageLabel;
    private javax.swing.JComboBox<String> receiverComboBox;
    private javax.swing.JLabel recentTransactionsLabel;
    private javax.swing.JTextField registerConfirmPasswordField;
    private javax.swing.JTextField registerEmailField;
    private javax.swing.JTextField registerFullNameField;
    private javax.swing.JButton registerLoginLink;
    private javax.swing.JLabel registerNewAccountPrompt;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField registerPasswordField;
    private javax.swing.JButton registerSubmit;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JLabel registerUsernameLabel1;
    private javax.swing.JLabel registerUsernameLabel2;
    private javax.swing.JLabel registerUsernameLabel3;
    private javax.swing.JButton regiterButton;
    private javax.swing.JButton regiterButton3;
    private javax.swing.JTextField resetConfirmPasswordField;
    private javax.swing.JLabel resetConfirmPasswordLabel;
    private javax.swing.JTextField resetEmailField;
    private javax.swing.JLabel resetEmailLabel;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JTextField resetPasswordField;
    private javax.swing.JLabel resetPasswordLabel;
    private javax.swing.JPanel resetPasswordPanel;
    private javax.swing.JButton sendMoneyButton;
    private javax.swing.JLabel sendMoneyLabel;
    private javax.swing.JMenuItem sendMoneyMenu;
    private javax.swing.JPanel startPanel;
    private javax.swing.JTextField transactAmountField;
    private javax.swing.JMenu transactMenu;
    private javax.swing.JPanel transactPanel;
    private javax.swing.JTable transactionsTable;
    private javax.swing.JMenu walletMenu;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel2;
    private javax.swing.JLabel welcomeLabel3;
    private javax.swing.JLabel welcomeMessageLabel;
    private javax.swing.JTextField withdrawAmountField;
    private javax.swing.JMenuItem withdrawMenu;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
